### ISSUE TITLE
Fozen all accounts, reason "Automatic mining software"

### ISSUE THREAD

**Issue by SlippingForest** [nhaidaar/hot-auto-claim#3]
who will use, keep this in mind

**Comment by hteppl** [comment]
It's because when you creating `claim` transaction from the backend, webapp adds csrf token.

**Comment by toastyy00** [comment]
is it possible to unfrozen it?

**Comment by SlippingForest** [comment]
> is it possible to unfrozen it?

Yes, don’t use autoclaim for a couple of days (and after)

**Comment by nthanhtung92** [comment]
hi, script still run but not claimming? 
Please update the script thanks.
